encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: pygments
pygments: true

# 作者信息
author: 
  name: janesy
  email: 1603734046@qq.com
  link: http://janesy.github.io/
  weibo: http://weibo.com/u/3315130274
  github: https://github.com/janesy
  github_username:  janesy
  weibo_username:  _youzyang

# 站点信息
title : 虎小萌的技术博客
description: 
 生活中的女汉子，IT界的萌妹子，
 努力了不一定会有收获，但不努力一定没有收获，
 努力做一个独一无二的程序狮
  
  
url: http://janesy.github.io/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/gavatar.png
favicon : /assets/img/favicon.png

# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : 时光如流水<br>一去不复返<br> 往者不可追<br>来者犹可惜<br>

# 首页除了最新文章外显示分类
cates: 
- Essay
# - Python
# - OpenStack

# 中文本地化
locals: 
   newest : 最新文章
